### PR TITLE
Updates for recent Hy changes

### PR DESCRIPTION
**Pull request by brandonwillard**
Beyond simple syntax and function signature updates, the biggest changes are in the handling/use of&mdash;the now missing&mdash;`cons`.

Also, some rules have been added that reflect the Hy language changes made in this commit.  Those additions still need tests.  

**A great test/demo of `hydiomatic` would be to use itself to apply the changes in this commit!**  Only a subset of changes could currently be performed with the ruleset additions; the other changes (e.g. the "lifting"/pulling out of `cons`es from quoted forms and additional `conde`s for the strict `list` type returned by the `cons` helper function) haven't been added, yet.  We might be able to add them, though, and/or use them as an opportunity to demonstrate user-level modifications/additions to `hydiomatic` rules.

### CODE REVIEW

**Comment by brandonwillard** [comment]
One test isn't passing and requires the fix from algernon/adderall#7.

Otherwise, the `let/when` macro pairing/unpacking rules are causing problems due to changes in the acceptable form for `let` bindings (e.g. from `(let [[[a b] [c d]] e] ...)` to `(let [a c b d e] ...)`).  As a result, simple acceptable forms like `(let [x 1] ...)` are mistakenly converted to `(let [x None 1 None] ...)`.

We need some more sophisticated pairing/zipping for `let/when` bindings; otherwise, we might just be able to separate these language updates by source and target versions and let the user decide which is which.  (That sounds lame, though.)  
For now, I could simply disable those rules so that this PR can go through.  @algernon, tell me if you have a preference for one or the other (or even something else).

Also, I'm trying to find a way to automatically add the `require`s and `import`s implied by the `let` and `cons` changes (i.e. move and removal, respectively).  I put code in place that will prepend those to the associated expressions, but that's clearly overkill, so I disabled them for now and only emit a warning in the log.

**Comment by algernon** [comment]
There are already rules which aren't enabled by default, adding some more, behind a new flag does not sound wrong. To be honest, I quite like the idea of being able to specify a source and a target version.

(Agree about the `require`/`import` stuff, its overkill to add them to every `let` and `cons`. The good option would be to treat the whole file as one big, implicit `do`, and have a rule that finds `let`/`cons` anywhere, and adds that to the beginning. And in the end, we unwrap the `do` and voila.)

**Comment by brandonwillard** [comment]
> (Agree about the require/import stuff, its overkill to add them to every let and cons. The good option would be to treat the whole file as one big, implicit do, and have a rule that finds let/cons anywhere, and adds that to the beginning. And in the end, we unwrap the do and voila.)

Exactly!  I just wasn't sure if we would want/need some awareness of scope, but I suppose top-level could do the trick (except for macros, at least until hylang/hy#1682 goes through).

**Comment by brandonwillard** [comment]
By the way, I think I'll just disable the problematic stuff, let this PR fix the Hy language changes in the core library, and start another for the source, target parameter/flag and new rules.

**Pull request merged**
